# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19b931ceda7c70f321e88f62f68ddfd6cd8952ca625219cbac1782d586a43ad83f182b5170d4e5650748a9bef49a7b6969d2b738e8c569af3be06434eb228a7

test:
  secret_key_base: 67201c749581689a48969c6533ab48ed68c9a49adb50a997522a3135b5dce5364d32126e3620f5bcbacdf5edf432d5d5f5ddb6694ff3d80acd9e763a8f8d88b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
